# Generated by Django 5.0.7 on 2024-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_favorite_tags_alter_favorite_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
